FROM alfresco/alfresco-content-repository:6.2.2.1
# COPY /properties/alfresco-global.properties /usr/local/tomcat/shared/classes/
ARG TOMCAT_LIB_DIR=/usr/local/tomcat/lib

COPY libs/. $TOMCAT_LIB_DIR‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍