
dependencies:
  - name: postgresql
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: alfresco-infrastructure
    version: 4.1.1
    condition: alfresco-process-services.alfresco-infrastructure.enabled
    repository: https://kubernetes-charts.alfresco.com/stable
