# This is a YAML-formatted file.  Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: quay.io/alfresco/alfresco-digital-workspace
  tag: "1.4.0"
  pullPolicy: Always
  internalPort: 8080
service:
  name: alfresco
  type: ClusterIP
  externalPort: 80
ingress:
  hostName: null
  path: /digital-workspace
  maxUploadSize: "5g"
  applicationBasePath: ./
resources:
  requests:
    memory: "250Mi"
  limits:
    memory: "500Mi"
  # The  readiness probe is used to check startup only as a failure
  # of the liveness probe later will result in the pod being restarted.
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 130
  periodSeconds: 20
  timeoutSeconds: 10

# choose if you want network policy enabled
networkpolicysetting:
  enabled: true

# If you are using a private image, define the alfrescoRegistryPullSecret value
# Global definition of Docker registry pull secret which can be overridden from parent ACS Helm chart(s)
global:
  alfrescoRegistryPullSecrets: quay-registry-secret
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
# # If you are deploying acs on a different path other than root you will need to pass in ACS_URL variable
# ACS_URL: https://example.com/acs