{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "aps.fullname" . }}-aps
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- if .Values.processEngine.ingress.maxUploadSize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.processEngine.ingress.maxUploadSize }}
    {{end}}

spec:
  rules:
    {{- if .Values.processEngine.ingress.hostName }}
    - host: {{ tpl .Values.processEngine.ingress.hostName $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
        - path: {{ tpl .Values.processEngine.ingress.path . }}
          backend:
            serviceName: {{ template "aps.fullname" . }}-aps
            servicePort: {{ .Values.processEngine.service.externalPort }}
{{- end }}
